const assert=require('node:assert/strict');
const {buildReportPlan,TYPES,UNVERIFIED}=require('../services/accountingReports');
const options={branches:[{BranchCode:'01'},{BranchCode:'02'}],accounts:[{ActCod:'100',BookType:'CB'},{ActCod:'500',AcNature:'5'}],levels:[{Row:0},{Row:1}],companyStart:'2026-06-01'};
const filters={fromDate:'2026-10-01',toDate:'2026-10-10',accountCodes:[],branchCodes:[],asOnDate:'2026-10-10'};
const plan=(id,f={})=>buildReportPlan(id,{...filters,...f},'UR',options);
assert.deepEqual(plan('accounting-ledger').params,['','2026-10-01','2026-10-10','L','AL','Cherrys','','ALL','0','Y','N','00000000000000','zzzzzzzzzzzz','Y','UR','N',',01,02,','C','V']);
assert.equal(plan('accounting-ledger',{dateBasis:'D'}).params[18],'D');
assert.equal(plan('trial-balance',{dateBasis:'D',reportLevel:'1'}).params[18],'V');
assert.equal(plan('trial-balance',{reportLevel:'1'}).params[8],'1');
assert.equal(plan('audit-trial',{voucherType:'BB',auditStatus:'EQUAL'}).params[4],'BB');
assert.equal(plan('audit-trial').params[10],'Y');
assert.equal(plan('month-wise-expense').params[0],',500,');
assert.equal(plan('daily-cash-bank-flow').params[0],',100,');
assert.equal(plan('month-wise-cash-bank').params[0],'');
assert.equal(plan('party-wise-collection',{view:'detail'}).reportType,'PWCD');
assert.equal(plan('party-wise-payment',{view:'detail'}).reportType,'PWPD');
assert.deepEqual(plan('receivable-aging').params,['UR','','2026-10-10','','BILLWISE','A','ALL','C',',01,02,','']);
assert.equal(plan('payable-aging',{agingView:'party-wise'}).reportType,'PARTYWISE');
assert.equal(plan('cash-bank-position').params[1],'2026-06-01');
assert.equal(plan('cash-bank-position').reportType,'B');
assert.equal(plan('chart-of-accounts').rows,options.accounts);
for(const id of Object.keys(TYPES)){const p=plan(id);if(p.procedure)assert.equal(p.params.length,p.procedure==='AccProc'?19:10);}
for(const id of UNVERIFIED)assert.throws(()=>plan(id),e=>e.code==='REPORT_NOT_CONFIGURED');
assert.throws(()=>plan('cash-bank-position',{view:'detail'}),/not verified/);
assert.throws(()=>plan('accounting-ledger',{branchCodes:['99']}),e=>e.statusCode===403);
assert.throws(()=>buildReportPlan('accounting-ledger',filters,'UR',{...options,branches:[]}),e=>e.statusCode===403);
assert.throws(()=>plan('accounting-ledger',{accountCodes:['999']}),/unavailable/);
assert.throws(()=>plan('accounting-ledger',{accountCodes:['100,500']}),/Invalid/);
assert.throws(()=>plan('accounting-ledger',{includeOpening:'Y'}),/Invalid/);
assert.throws(()=>plan('accounting-ledger',{fromDate:'2026-02-30'}),/Invalid/);
assert.throws(()=>plan('accounting-ledger',{fromDate:'2026-11-01'}),/From date/);
assert.throws(()=>plan('trial-balance',{reportLevel:'99'}),/Invalid/);
assert.throws(()=>plan('month-wise-expense',{accountCodes:['100']}),/category/);
assert.throws(()=>plan('unknown'),/Unknown/);
console.log('PASS: 15 verified report contracts, procedure positions, date and type validation, branch restrictions, category restrictions, and unsupported mappings');
